name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    
    - name: Build bottles
      run: |
        brew test-bot --only-cleanup-before
        brew test-bot --only-setup
        brew test-bot --only-formulae --keep-old
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
    
    - name: Upload bottles
      uses: actions/upload-artifact@v4
      with:
        name: bottles
        path: '*.bottle.*'
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for version ${{ github.ref_name }}
          
          Install with:
          ```bash
          brew tap emocharnik/scalr
          brew install scalr
          ```
        draft: false
        prerelease: false
        files: '*.bottle.*'